[package]
name = "oidc-cli"
version = "0.1.0"
edition = "2021"

authors = ["Jens Reimann <ctron@dentrassi.de>"]
license = "Apache-2.0"
repository = "https://github.com/ctron/oidc-cli"
categories = ["command-line-utilities", "authentication"]
keywords = ["oidc", "cli"]
readme = "README.md"
# based on clap
rust-version = "1.74"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
directories = "5"
log = "0.4"
openid = "0.12"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
simplelog = "0.12"
tokio = { version = "1.36", features = ["full"] }
url = "2"
